### ISSUE TITLE
Create a GitHub IO page

### ISSUE THREAD

**Issue by guibranco** [guibranco/BancosBrasileiros#13]
Create a github.io page with:

- A table of banks for search & filter;
- A "new bank" widget to easily add a new bank that add the data to all formats and allow download theses formats with this new bank;
- Allow download of files (XML, CSV, SQL, JSON) without changes;

**Comment by rodrigondec** [comment]
This "new bank" widget is not easily done, as the files are persisted on github. The script would need to make a commit and push

**Comment by guibranco** [comment]
The idea is not to persist on the GH, but allow to download immediately by the user. I think this was not clear in my previous comment. 

But I liked your idea, opening a PR with GH API would be nice, but is a little bit hard haha
We can also use a external data source, like Firebase ou a MySQL/Redis on a cloud provider within free tier
