### ISSUE TITLE
Bancos com o mesmo codigo

### ISSUE THREAD

**Issue by RauppAndPony** [guibranco/BancosBrasileiros#16]
**Describe the bug**

``Banco NEON`` e ``Banco Potencial`` estão com o mesmo código ``735``

Also ``Banco Potencial`` está com um erro de digitação (``"BACO POTENCIAL"``)

**Screenshots**

![image](https://user-images.githubusercontent.com/53233459/68533299-6a77e080-02ec-11ea-8085-3a4423a5f17c.png)
![image](https://user-images.githubusercontent.com/53233459/68533302-719eee80-02ec-11ea-92f2-4b92fbda195a.png)

**Additional context**

Esses problemas estão ocorrendo no arquivo [bancos.json](https://github.com/guibranco/BancosBrasileiros/blob/master/bancos.json), não sei se aplica para os outros formatos.

**Comment by guibranco** [comment]
Vou corrigir!
