### ISSUE TITLE
Erro de execução SQL

### ISSUE THREAD

**Issue by rafaeldomi** [guibranco/BancosBrasileiros#205]
**Describe the bug**
ERROR:  syntax error at or near "s"
LINE 1: ...VALUES('298','17772370','17.772.370/0001-40','Vip's Corretor...

**To Reproduce**
Rodar o arquivo schema.sql no banco, com psql -f schema.sql

Rodando em postgresql

**Comment by guibranco** [comment]
Obrigado por abrir a issue a PR.
A PR foi aprovada, porém preciso corrigir a ferramenta que gera o arquivo automaticamente para que não desfaça sua correção futuramente.

**Comment by guibranco** [comment]
Corrigido!
