### ISSUE TITLE
Create a sample example in PHP/Composer/Packagist

### ISSUE THREAD

**Issue by guibranco** [guibranco/BancosBrasileiros#227]
**Is your feature request related to a problem? Please describe.**
Create a sample project in PHP using the Packagist/Composer package.

**Describe the solution you'd like**
Create a sample project in the **examples** directory for PHP, using the Packagist package and unserializing the banks.json file and showing it from PHP as a table or something else.

**Comment by AmolKumarGupta** [comment]
Hi @guibranco , can I do this issue.
if yes, please assign this to me, 
And do you want project in samples directory or examples directory ??

**Comment by guibranco** [comment]
Of course, assigned! 

Thanks in advance
