### ISSUE TITLE
Nubank wrong name

### ISSUE THREAD

**Issue by rodrigondec** [guibranco/BancosBrasileiros#23]
Bank 260 "nubank" is actually "Nu Pagamentos S.A"

https://blog.nubank.com.br/nu-pagamentos-sa/

Code: 260
Name: Nu Pagamentos S.A
Fantasy Name: Nubank
Document: 18.236.120/0001-58
Website: https://nubank.com.br/en/

**Comment by guibranco** [comment]
Aprovado!
