### ISSUE TITLE
"Banco de Brasília" typo

### ISSUE THREAD

**Issue by luisccf** [guibranco/BancosBrasileiros#25]
"BANCO DE BRASÍLIA" is written as "BANCO DE BRASÌLIA" (note the back tick on the I) on both csv and json files.

#### bancos.csv
```
"070";"BRB - BANCO DE BRASÌLIA";"";"2017-04-19 15:58:17.387";;;false
```

#### bancos.json
```
  {
    "Code": "070",
    "Name": "BRB - BANCO DE BRASÌLIA",
    "CreatedAt": "2017-04-19 15:58:17.387",
    "UpdatedAt": null,
    "DeletedAt": null,
    "IsDeleted": false
  },
```

I can open a pull request with the fix if it really is a typo.

**Comment by guibranco** [comment]
If you can open a PR, I'll appreciate

**Comment by guibranco** [comment]
Awaiting the PR @luisccf
