### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by RauppRafael** [guibranco/BancosBrasileiros#30]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
package.json files allows us to donwload this repo using NPM
running ``npm init`` will promp you some questions to generate this file

**Additional context**
You can take a step further and add it to https://www.npmjs.com/

**Comment by guibranco** [comment]
Done!

**Comment by RauppRafael** [comment]
Can you publish it to https://www.npmjs.com/?

**Comment by guibranco** [comment]
I tried, but looks like that someone else already did this with my repo, I'm looking for a way to turn over it and publish it anyway, maybe the only way would be renaming the package for something else than "bancosbrasileiros". Listening for options...

**Comment by guibranco** [comment]
Published as "bancos-brasil" package.

https://www.npmjs.com/package/bancos-brasil


```bash

npm i bancos-brasil

```

**Comment by RauppRafael** [comment]
I've published this package a few months ago: https://www.npmjs.com/package/bancos-brasileiros 

If you prefer I could add you as the owner.

**Comment by RauppRafael** [comment]
Done, I've added you as the owner

**Comment by RauppRafael** [comment]
Sorry for publishing your package, I needed to include it in one of my projects and didn't wanna bother you..

**Comment by guibranco** [comment]
No problems bro! Thanks for doing that! I'll change again the name and upload to this package!
