### ISSUE TITLE
Seria  possível utilizar em um package feito em dart?

### ISSUE THREAD

**Issue by maurojohann** [guibranco/BancosBrasileiros#310]
Olá Pessoa, preciso resolver o ISPB que consumo de uma api, mas isso precisa ser feito em dart, pois ira rodar em um app mobile, e estou usando Flutter. 

Pensei em consumir diretamente o bancos.json do repositório, salva-lo localmente no app, e eventualmente atualiza-lo. 

Eu poderia estar criando um package em dart que fizesse isso, e salva-lo em sqfLite, apenas para não precisar consumir a todo momento o repositório. Mas eu não sei se está seria a melhor opção. Gostaria da opinião de vocês, talvez com algumas dicas possamos ter uma package em dart também. 

Será que está seria a melhor opção?

**Comment by guibranco** [comment]
Bom dia @maurojohann 

Acredito que baixando o arquivo JSON e mantendo localmente já resolva seu problema.
Eu não tenho experiência com DART, não sei como funciona o sistema de pacotes dele, mas posso dar uma pesquisada e botar no backlog para criar esse pacote também.

Atualmente a lista é atualizada diariamente, mas se você olhar o changelog vai ver que faz mais de 10 dias que não tivemos alterações. O último banco adicionado (não atualizado) foi no dia 30/08/2023, antes disso tinha sido em 2022 apenas (falando de STR), a lista do PIX fornecida pelo Banco Central, é atualizada diariamente, porém nem sempre temos alterações.

Acho que o download pra sua aplicação direto do repositório e um cache semanal (ou até mesmo mensal) seria o suficiente.

**Comment by guibranco** [comment]
@maurojohann vou encerrar esta issue.

Criei uma issue para criar o pacote para Dart, talvez alguém pegue ela, ou no futuro, eu mesmo criei, só preciso achar um tempo...

Issue para o pacote DART: #312

**Comment by maurojohann** [comment]
@guibranco obrigado, vou ver se consigo ajudar.
