### ISSUE TITLE
Add support to Pub.Dev - Dart

### ISSUE THREAD

**Issue by guibranco** [guibranco/BancosBrasileiros#312]
Publish this project to Pub.Dev (Dart) package manager

**Comment by Guillergood** [comment]
I have some experience in Dart, may I help on this?

**Comment by guibranco** [comment]
Ho @Guillergood , we need to create a package publishable to Pub.Dev with the content of a file

The file is: [data/bancos.json](https://github.com/guibranco/BancosBrasileiros/blob/main/data/bancos.json)

- This file is generated in a daily bases or on demand any time.
- The generation and deployment of the Dart package should be done in the AppVeyor pipeline (via appveyor.yml file)
- I think that we need to create a `pubspec.yaml`, is that correct?

The package should have the following behavior:

When installed in a Dart project, it should contain the `bancos.json` file or maybe the content only available for usage inside the code.

I don't know how exactly Dart pure packages works or if this is possible, but this is the goal.
You can check the NPM (JS) / NuGet (C#) / Packagist (PHP) packages to understand how it should be for Dart!


Thanks!

**Comment by Guillergood** [comment]
Hello @guibranco , sorry for the late response. I think I have it all, can you check it?

**Comment by guibranco** [comment]
Thanks, I am reviewing it right now!
