### ISSUE TITLE
Update `README.md` file in the examples directory

### ISSUE THREAD

**Issue by guibranco** [guibranco/BancosBrasileiros#321]
**Describe the bug**
The `README.md` files in the [examples/dotnet/README.md](https://github.com/guibranco/BancosBrasileiros/blob/main/examples/dotnet/Readme.md) and [examples/php/README.md](https://github.com/guibranco/BancosBrasileiros/blob/main/examples/php/Readme.md) directories are outdated.

**Expected behaviour**
The table `available data` in these documents should match the table that exists at the root level of the repository: [README.md](https://github.com/guibranco/BancosBrasileiros/blob/main/README.md)

**Comment by sahalhes** [comment]
@guibranco  Hey can you please assign this issue to me?

**Comment by sahalhes** [comment]
@guibranco Hey I have done PR, kindly tell if there are any changes required.

**Comment by guibranco** [comment]
I will review it in the next hour!

Thanks!

**Comment by guibranco** [comment]
@sahalhes assigned and approved!

**Comment by sahalhes** [comment]
@guibranco Thanks !
