### ISSUE TITLE
Banco Inter ainda está como Intermedium

### ISSUE THREAD

**Issue by iurisilvio** [guibranco/BancosBrasileiros#40]
O Banco Inter (077) está com nome desatualizado (Intermedium) no JSON, CSV e XML.

https://github.com/guibranco/BancosBrasileiros/blob/master/bancos.csv#L7
https://github.com/guibranco/BancosBrasileiros/blob/cd5dcd2157c7bf5ab9ccc4012a77268af0b71f22/bancos.json#L45
https://github.com/guibranco/BancosBrasileiros/blob/cd5dcd2157c7bf5ab9ccc4012a77268af0b71f22/bancos.xml#L50

**Comment by guibranco** [comment]
Feito!
