### ISSUE TITLE
Sql (Banco 733) sem o conteúdo do campo UpdateAt

### ISSUE THREAD

**Issue by silverio27** [guibranco/BancosBrasileiros#41]
O Banco 733 está sem o conteúdo do campo UpdateAt na cláusula Values.

**Comment by guibranco** [comment]
Os itens que estão presentes na lista desde o começo não possuem o valor da coluna UpdateAt em nenhuma das listas. Diversos outros itens estão sem esse valor e só serão preenchidos no momento que sofrerem alteração. Deve-se considerado como um campo "NULL" e não "NOT NULL" na modelagem de dados.

**Comment by silverio27** [comment]
Oi Guilherme, errei o banco é o 735!. Ele não possui o conteúdo 'NULL' na clausula como nos demais. Ao tentar inserir retorna o erro que a quantidade de valores informados não é equivalente a quantidade de campos informados.  'INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `UpdatedAt`, `IsDeleted`) VALUES (735,'BANCO NEON', '', 1);

**Comment by guibranco** [comment]
Corrigindo!

**Comment by guibranco** [comment]
Feito @silverio27, obrigado!

**Comment by silverio27** [comment]
Show!
