### ISSUE TITLE
[BUG] faltando uma vírgula no objeto do último banco

### ISSUE THREAD

**Issue by Lets-DavIt** [guibranco/BancosBrasileiros#442]
### Description

Está faltando uma vírgula no último banco da listagem após "Url": null 

segue evidencia:

{
    "COMPE": "757",
    "ISPB": "02318507",
    "Document": "02.318.507/0001-13",
    "LongName": "BANCO KEB HANA DO BRASIL S.A.",
    "ShortName": "BCO KEB HANA DO BRASIL S.A.",
    "Network": "RSFN",
    "Type": "Banco Comercial",
    "PixType": "DRCT",
    "Charge": true,
    "CreditDocument": true,
    "LegalCheque": false,
    "DetectaFlow": false,
    "PCR": true,
    "PCRP": false,
    "SalaryPortability": null,
    "Products": null,
    "Url": null 
    "DateOperationStarted": "2002-04-22",
    "DatePixStarted": "2021-08-09 10:00:00",
    "DateRegistered": "2021-05-05T09:11:12.7114464-03:00",
    "DateUpdated": "2024-05-15T16:49:45.7313357+00:00"
  }

### Screenshots

![image](https://github.com/user-attachments/assets/20fd92d9-85dc-4da6-a2ce-c77c6a03e617)

**Comment by guibranco** [comment]
@Lets-DavIt obrigado pelo aviso! Corrigido!
