### ISSUE TITLE
Código Santander errado no bancos.sql

### ISSUE THREAD

**Issue by raframil** [guibranco/BancosBrasileiros#46]
Há uma divergência entre os arquivos SQL e CSV. No SQL, o código 033 está como **BANCO DO ESTADO DE SAO PAULO S.A**, sendo que deveria ser Santander. No CSV aparentemente está correto, mas o 502 está como Santander também (em ambos, SQL e CSV).

**Comment by guibranco** [comment]
Já será corrigida na versão 2.0! 
Pretendo liberar essa versão ainda hoje...

Obrigado pelo aviso!

**Comment by guibranco** [comment]
Atrasei a versão 2, vou arrumar nessa e na dois quando lançar...

**Comment by guibranco** [comment]
Corrigido!

Versão do NPM 1.2.26
