### ISSUE TITLE
Fix typo for bank with COMPE 014

### ISSUE THREAD

**Issue by mdapper** [guibranco/BancosBrasileiros#82]
**Describe the bug**

looks like there's a typo on the `LongName` of the bank with `"COMPE": "014"`.

**To Reproduce**

Check the `LongName` for the bank with `"COMPE": "014"`, currently have the value with a `?` as fallowed:

```
"LongName": "STATE STREET BRASIL S.A. ? BANCO COMERCIAL",
```

**Expected behavior**

It should be:

```
"LongName": "STATE STREET BRASIL S.A. - BANCO COMERCIAL",
```

**Additional context**

If that's the case I can open a PR with the fix.

**Comment by guibranco** [comment]
I'll check and provide a way to fix this definitely, because we don't want this to be wrong again on the monthly updates that are generated by `MergeTool`

**Comment by guibranco** [comment]
This bank is only available on the [STR file](http://www.bcb.gov.br/pom/spb/estatistica/port/ParticipantesSTRport.csv), and there, is already the typo error. 

What do you think @mdapper ? We replace `?` from `STR file` with `-` or continue this way ? 

I don't have other source for this specific item to compare and use as "correct" one

**Comment by mdapper** [comment]
If you use the STR file as the source material to get the data maybe it could keep as it is. I am using the JSON in an application and found curious a bank name with a `?`, it looked like a typo. I searched on Google and found references using the `-`, that's why I opened this issue.

It will not impact my use if stays the same.

**Comment by guibranco** [comment]
I made a change on the `MergeTool`, so now every `?` on the STR will be replaced by `-`
